name: Build APK Final

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Changed from 18 to 20 for Vite 7
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Fix and build frontend
      run: |
        cd frontend
        
        echo "=== Fixing vite.svg import ==="
        # Remove vite.svg import from App.tsx
        sed -i '/import viteLogo from/d' src/App.tsx
        sed -i '/<img src={viteLogo}/d' src/App.tsx
        
        # Remove vite.svg from index.html
        sed -i '/vite\.svg/d' index.html
        
        echo "=== Installing dependencies ==="
        # Use npm install instead of npm ci since package-lock is out of sync
        npm install
        
        echo "=== Building ==="
        npm run build
        
        echo "=== Fixing paths ==="
        sed -i 's|href="/|href="./|g' dist/index.html 2>/dev/null || true
        sed -i 's|src="/|src="./|g' dist/index.html 2>/dev/null || true
        
        echo "=== Setting up Android ==="
        # Remove existing android directory if it exists
        rm -rf android
        
        # Add Android platform
        npx @capacitor/cli add android
        
        # Sync
        npx cap sync android
        
        echo "=== Building APK ==="
        cd android
        
        # Ensure gradlew exists and is executable
        if [ ! -f gradlew ]; then
          echo "gradlew not found, running gradle wrapper"
          gradle wrapper
        fi
        
        chmod +x gradlew
        
        # Build APK
        ./gradlew app:assembleDebug --stacktrace
        
        echo "=== Finding APK ==="
        find . -name "*.apk" -type f -ls
        
        # Copy APK to a known location
        mkdir -p ../../apk-output
        cp app/build/outputs/apk/debug/*.apk ../../apk-output/ || echo "APK copy failed"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: final-apk-${{ github.run_number }}
        path: apk-output/*.apk
        retention-days: 30
        if-no-files-found: error
    
    - name: Summary
      run: |
        echo "## ✅ APK Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Key Fixes Applied:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Node.js 20 for Vite 7 compatibility" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Removed vite.svg references" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Fixed package-lock sync issues" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Handled missing gradlew" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Download the APK from the artifacts above!" >> $GITHUB_STEP_SUMMARY